[package]
name = "FinSc-Multiset-Transform"
version = "0.3.1"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"
